---
name: Docker Build
description: Builds a container image
author: https://github.com/equinixmetal-buildkite
requirements:
  - docker
configuration:
  properties:
    dockerfile:
      type: string
      description: The path to the Dockerfile.
      default: Dockerfile
    context:
      type: string
      description: The path to the context directory.
      default: .
    secret-file:
      type: string
      description: A string like 'id=mysecret,src=secret-file' where <secret-file> is the path in the build (This enables Docker Buildkit, also)
    tags:
      type: array
      description: A list of tags to build (can also detect tags from docker-metadata-buildkite-plugin)
    labels:
      type: array
      description: A list of labels to build (can also detect tags from docker-metadata-buildkite-plugin)
    push:
      type: boolean
      description: Whether to push the image to the registry.
      default: false
  additionalProperties: false
